//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Code_Tool.SDK.Utils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebdavResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebdavResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QR_Code_Tool.SDK.Utils.WebdavResources", typeof(WebdavResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://oauth.yandex.ru/authorize?response_type=token&amp;client_id={0}&amp;display=popup.
        /// </summary>
        internal static string AuthBrowserUrlFormat {
            get {
                return ResourceManager.GetString("AuthBrowserUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect parameters - provide correct data and try again.
        /// </summary>
        internal static string BadParameterErrorMesage {
            get {
                return ResourceManager.GetString("BadParameterErrorMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect request - provide correct data and try again.
        /// </summary>
        internal static string BadRequestErrorMessage {
            get {
                return ResourceManager.GetString("BadRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e44807741c564ca9bcbf3cb14ef20be5.
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must be logged in before starting to work with SDK, try to call AuthorizeAsync(...) at first.
        /// </summary>
        internal static string NotAuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file is too large for uploading.
        /// </summary>
        internal static string OutOfMemoryErrorMessage {
            get {
                return ResourceManager.GetString("OutOfMemoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t load SDK provider assembly. Add reference to the platform specific assembly &apos;Disk.SDK.Provider (platform)&apos; and try again..
        /// </summary>
        internal static string ProviderErrorMessage {
            get {
                return ResourceManager.GetString("ProviderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://127.0.0.1:130/test.
        /// </summary>
        internal static string ReturnURL {
            get {
                return ResourceManager.GetString("ReturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ([a-zA-Z0-9]){53}.
        /// </summary>
        internal static string TokenRegexPattern {
            get {
                return ResourceManager.GetString("TokenRegexPattern", resourceCulture);
            }
        }
    }
}
